services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: puccomp
      POSTGRES_USER: puccomp
      POSTGRES_PASSWORD: puccomp
    ports:
      - "5432:5432"

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025" # mailpit web ui: http://localhost:8025
