services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"     # Única porta exposta para o mundo HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
      - grafana

  api:
    image: ghcr.io/puccomp/puccomp-api-v2:latest
    env_file:
      - .env #Necessario ser apenas .env por reconhecimento do EC2 não altere isso
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/puccomp
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - SPRING_PROFILES_ACTIVE=prod
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: puccomp
    volumes:
      - pgdata:/var/lib/postgresql/data # Garante que os dados não somem
    # O Flyway vai rodar automaticamente quando a API do Spring Boot iniciar

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # Sem 'ports', fica 100% interno

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
      - GF_SERVER_ROOT_URL=https://api.puccomp.com.br/grafana/
      - GF_SERVER_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    # Nginx vai rotear o tráfego para ele internamente na porta 3000

  node_exporter:
    image: prom/node-exporter:latest
    # Sem ports

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0 # Versão compatível com ARM64
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    # Sem ports

volumes:
  pgdata:
  grafana_data: