spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/puccomp
    username: puccomp
    password: puccomp
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

puccomp:
  security:
    jwt:
      secret: dev-secret-change-me-please-pelo-menos-32-bytes-0123456789
  onboarding:
    accept-url-base: http://localhost:8080/aceitar-convite
  admin:
    key: dev-admin-key

management:
  tracing:
    sampling:
      probability: 1.0
