global:
  scrape_interval: 15s

scrape_configs:
  - job_name: puccomp-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]  # app roda no host, não em container
